# Site
title: 孙云增的博客
subtitle: 极简生活，极致内涵
description: 极简生活，极致内涵
keywords: 博客 孙云增
author: 孙云增
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://sunyunzeng.com
root: /
permalink: :title/  # :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase

external_link: 
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: '' 

filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: 
    github: git@github.com:SUNYunZeng/SUNYunZeng.github.io.git
    coding: git@e.coding.net:SUNYunZeng/SUNYunZeng.git
  branch: master
- type: baidu_url_submitter

baidu_url_submit:
  count: 10 ## 比如3，代表提交最新的三个链接
  host: sunyunzeng.com ## 在百度站长平台中注册的域名
  token: QVaeidVy7RwSqiqP ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里


# 抓取设置
sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml

  # hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
  - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
  - '*.min.js'

 
# 站内搜索
jsonContent:
  ignore:
    - path/to/a/page
    - url/to/one/post
    - an-entire-category
    - specific.file
    - .ext # a file extension
  meta: true
  dafts: false
  file: content.json
  dateFormat: YYYY-MM-DD
  posts:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    text: true
    categories: true
    tags: true
  # pages:
  #   title: true
  #   date: false
  #   updated: false
  #   comments: false
  #   path: false
  #   permalink: true
  #   excerpt: false
  #   text: false
  
  # 我的猫
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hijiki
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7

# RSS分享
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 50
  hub:
  content:
  content_limit: 200
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
  
# 博客内容加密
encrypt:
    enable: true
    abstract: 有东西被加密了, 请输入密码查看.
    message: 您好, 这里需要密码.

    wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
    wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

plugins:
  - hexo-algoliasearch

algolia:
  appId: "9ZTBGDFSAP"
  apiKey: "a7c43d4d2107e77dafed3ed5e01c6d5f"
  adminApiKey: "3d1283134b60adbdb921be186e903411"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title


## 豆瓣读书
douban:
  user: 178089077
  builtin: true
  book:
    title: '我的书单'
    quote: '读书破万卷，下笔如有神'
    meta: true
    comments: false
    top_img: https://cdn.jsdelivr.net/gh/SUNYunZeng/sources/img/book.png
    aside: true
  movie:
    title: '看过的电影'
    quote: '电影人生'
    meta: true
    comments: false
    top_img: https://cdn.jsdelivr.net/gh/SUNYunZeng/sources/img/movie.png
    aside: true
  # game:
  #   title: 'This is my game title'
  #   quote: 'This is my game quote'
  #   meta: true
  #   comments: true
  #   top_img: https://cccccc.png
  #   aside: true
  timeout: 10000

Markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false